theme: jekyll-theme-midnight
title: Skybreaker Projects
description: This page was created to track/showcase my progress towards becoming a software developer and hopefully show it to a future employer!
